# EMBY SETTINGS
[http.routers]
  [http.routers.emby]
    entrypoints = ["websecure"]
    service = "emby"
    rule = "Host(`emby.depuydt-lauwereins.be`)"
    [http.routers.emby.tls]
      certResolver = "tls"

[http.services]
  [http.services.emby.loadBalancer]
    [[http.services.emby.loadBalancer.servers]]
      url = "http://192.168.1.20:8096/web/dashboard.html"
