# NETGEAR SETTINGS
[http.routers]
  [http.routers.netgear]
    entrypoints = ["websecure"]
    service = "netgear"
    rule = "Host(`netgear.depuydt-lauwereins.be`)"
    [http.routers.netgear.tls]
      certResolver = "tls"

[http.services]
  [http.services.netgear.loadBalancer]
    [[http.services.netgear.loadBalancer.servers]]
      url = "http://192.168.1.3"
